import streamlit as st

st.set_page_config(page_title="Compliance Mapping", layout="wide")

# --- Page Header ---
st.title("Compliance Mapping")
st.caption("Review extracted obligations and map them to system requirements")

# --- Left Column: Clause List ---
left, right = st.columns([1, 2])

with left:
    st.subheader("Clauses")
    st.text_input("🔍 Search clauses", "")
    framework = st.selectbox("Filter by Framework", ["All", "GDPR", "Basel", "PCI-DSS", "SOX", "HIPAA"])
    status = st.selectbox("Filter by Status", ["All", "Approved", "Pending", "Rejected"])

    # Example clauses list
    clauses = [
        {"id": "GDPR-A32-1", "text": "Data Security Requirements", "status": "Approved"},
        {"id": "Basel-III-CR-12", "text": "Credit Risk Assessment", "status": "Pending"},
        {"id": "GDPR-A71", "text": "Right to Erasure", "status": "Pending"},
        {"id": "PCI-DSS-3.2.1", "text": "Cardholder Data Protection", "status": "Pending"},
        {"id": "SOX-404-IT", "text": "IT Controls Assessment", "status": "Pending"},
        {"id": "HIPAA-HC-312", "text": "Technical Safeguards", "status": "Pending"},
    ]

    for clause in clauses:
        st.write(f"**{clause['id']}** — {clause['text']} ({clause['status']})")

    # Navigation
    col1, col2 = st.columns([1, 1])
    with col1:
        st.button("⬅️ Previous Clause")
    with col2:
        st.button("Next Clause ➡️")

# --- Right Column: Clause Details + Mapping ---
with right:
    st.subheader("GDPR-A32-1: Data Security Requirements")
    st.caption("Last updated: Aug 22, 2025 by John Smith")

    st.markdown("**Original Clause**")
    st.info(
        "The controller and the processor shall implement appropriate technical and "
        "organizational measures to ensure a level of security appropriate to the risk, "
        "including pseudonymisation and encryption of personal data..."
    )

    st.markdown("**System Requirements Mapping**")

    # Example autogenerated requirements
    st.write("Requirement #1 (Auto-generated)")
    st.text_area(
        "Requirement Text",
        "Implement data encryption for all personal data at rest and in transit using "
        "industry-standard encryption algorithms (AES-256 or equivalent).",
        height=80
    )
    st.selectbox("Priority", ["High", "Medium", "Low"], index=0)
    st.selectbox("Assignee", ["Security Team", "Compliance Team", "Engineering"], index=0)

    st.write("Requirement #2 (Auto-generated)")
    st.text_area(
        "Requirement Text",
        "Establish a regular backup schedule with tested recovery procedures to ensure data "
        "can be restored within the defined RTO (Recovery Time Objective) of 4 hours.",
        height=80
    )
    st.selectbox("Priority", ["High", "Medium", "Low"], index=1)
    st.selectbox("Assignee", ["Security Team", "Compliance Team", "Engineering"], index=2)

    # SME actions
    st.markdown("**Reviewer Actions**")
    col1, col2, col3, col4 = st.columns([1, 1, 1, 1])
    with col1:
        st.button("✅ Approve")
    with col2:
        st.button("✏️ Edit")
    with col3:
        st.button("❌ Reject")
    with col4:
        st.button("🔄 Regenerate")

    # Progress bar (example: 12 of 45 clauses reviewed)
    st.progress(12 / 45)
    st.caption("12 of 45 Clauses Reviewed")
