name: Deploy RCT UI

on:
  push:
    branches:
      - release/v1.0.0   # ✅ only deploy from release branch
  pull_request:
    branches:
      - release/v1.0.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t rct-ui .

      - name: Run Tests
        run: echo "✅ Tests placeholder" # replace with pytest later

      - name: Deploy to Streamlit Cloud
        run: echo "Streamlit Cloud auto-deploys from release/v1.0.0"
